/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    categories: Category;
    materials: Material;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers: Customer;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive text for accessibility, SEO, and screen readers.
   */
  alt: string;
  /**
   * Optional image caption for editorial displays.
   */
  caption?: string | null;
  /**
   * Set by the media seed. Identifies a migrated asset.
   */
  migrationKey?: string | null;
  /**
   * Original remote URL this asset was imported from.
   */
  sourceUrl?: string | null;
  /**
   * Placeholder photography. Replace before launch.
   */
  temporaryAsset?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  name: string;
  slug: string;
  baseFamily: 'pla' | 'petg' | 'tpu' | 'abs' | 'asa' | 'pa-nylon' | 'pc' | 'hips' | 'pva-support' | 'other';
  subtype?: string | null;
  modifiers?: ('carbon-fiber' | 'glass-fiber' | 'wood-filled' | 'metal-filled' | 'glow' | 'other')[] | null;
  description?: string | null;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | Customer;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInNPREnabled?: boolean | null;
  priceInNPR?: number | null;
  /**
   * Variant photography for customer-facing display
   */
  images?: (number | Media)[] | null;
  sku?: string | null;
  /**
   * Threshold below which low-stock warnings trigger
   */
  lowStockThreshold?: number | null;
  /**
   * Disabled variants will not be purchasable on storefront
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInNPREnabled?: boolean | null;
  priceInNPR?: number | null;
  title: string;
  /**
   * URL identifier. Auto-generated from title when left empty.
   */
  slug: string;
  /**
   * Used for product cards, listings and search previews
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  featured?: boolean | null;
  productType: 'filament' | '3d-print';
  category?: (number | null) | Category;
  filamentDetails?: {
    brand?: 'Numakers' | null;
    material?: (number | null) | Material;
    finish?:
      | (
          | 'basic'
          | 'matte'
          | 'silk'
          | 'glossy'
          | 'metallic'
          | 'transparent'
          | 'translucent'
          | 'sparkle'
          | 'marble'
          | 'gradient'
          | 'dual-color'
          | 'tri-color'
          | 'glow'
          | 'wood'
          | 'other'
        )
      | null;
    /**
     * Aura sells only 1.75 mm filament
     */
    diameter?: number | null;
    /**
     * Aura sells only 1 kg filament spools
     */
    netWeightKg?: number | null;
    technicalSpecifications?: {
      nozzleTempMin?: number | null;
      nozzleTempMax?: number | null;
      bedTempMin?: number | null;
      bedTempMax?: number | null;
      printSpeedMin?: number | null;
      printSpeedMax?: number | null;
      density?: number | null;
      drying?: {
        recommended?: boolean | null;
        temperature?: number | null;
        durationHours?: number | null;
      };
      enclosure?: ('not-required' | 'recommended' | 'required') | null;
      hardenedNozzle?: ('not-required' | 'recommended' | 'required') | null;
      amsCompatibility?: ('compatible' | 'not-compatible' | 'conditional' | 'unknown') | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  /**
   * Link canonical material if this Option belongs to Material Variant Type
   */
  material?: (number | null) | Material;
  /**
   * Select color family if this Option belongs to Color Variant Type
   */
  colorFamily?:
    | (
        | 'black'
        | 'white'
        | 'gray'
        | 'red'
        | 'orange'
        | 'yellow'
        | 'green'
        | 'blue'
        | 'purple'
        | 'pink'
        | 'brown'
        | 'beige'
        | 'gold'
        | 'silver'
        | 'transparent'
        | 'multicolor'
        | 'other'
      )
    | null;
  /**
   * Optional hex code in format #RRGGBB (e.g. #15A246)
   */
  hexColor?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | Customer;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'NPR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | Customer;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'NPR' | null;
  orderNumber?: string | null;
  /**
   * Unique client idempotency key to prevent duplicate orders
   */
  idempotencyKey?: string | null;
  paymentMethod?: ('esewa_qr' | 'cod') | null;
  paymentStatus?: ('unpaid' | 'awaiting_verification' | 'paid' | 'refunded') | null;
  /**
   * Customer-supplied transaction or reference ID
   */
  paymentReference?: string | null;
  subtotal?: number | null;
  shipping?: number | null;
  orderNotes?: string | null;
  /**
   * Immutable snapshot of purchased items at checkout time
   */
  itemsSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | Customer;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'NPR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  migrationKey?: T;
  sourceUrl?: T;
  temporaryAsset?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  baseFamily?: T;
  subtype?: T;
  modifiers?: T;
  description?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInNPREnabled?: T;
  priceInNPR?: T;
  images?: T;
  sku?: T;
  lowStockThreshold?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  material?: T;
  colorFamily?: T;
  hexColor?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInNPREnabled?: T;
  priceInNPR?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  featured?: T;
  productType?: T;
  category?: T;
  filamentDetails?:
    | T
    | {
        brand?: T;
        material?: T;
        finish?: T;
        diameter?: T;
        netWeightKg?: T;
        technicalSpecifications?:
          | T
          | {
              nozzleTempMin?: T;
              nozzleTempMax?: T;
              bedTempMin?: T;
              bedTempMax?: T;
              printSpeedMin?: T;
              printSpeedMax?: T;
              density?: T;
              drying?:
                | T
                | {
                    recommended?: T;
                    temperature?: T;
                    durationHours?: T;
                  };
              enclosure?: T;
              hardenedNozzle?: T;
              amsCompatibility?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  orderNumber?: T;
  idempotencyKey?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentReference?: T;
  subtotal?: T;
  shipping?: T;
  orderNotes?: T;
  itemsSnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    image?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  categories?: {
    enabled?: boolean | null;
    items?:
      | {
          title?: string | null;
          subtitle?: string | null;
          url?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  popular?: {
    enabled?: boolean | null;
    heading?: string | null;
    /**
     * Product records stay the source of truth for title, image, price.
     */
    products?: (number | Product)[] | null;
  };
  materialsSection?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          material?: (number | null) | Material;
          /**
           * Optional override. Falls back to the linked material name.
           */
          displayName?: string | null;
          description?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  useCases?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          title?: string | null;
          subtitle?: string | null;
          url?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  freshPrints?: {
    enabled?: boolean | null;
    heading?: string | null;
    viewAll?: {
      label?: string | null;
      url?: string | null;
    };
    products?: (number | Product)[] | null;
  };
  staffPick?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
    product?: (number | null) | Product;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  /**
   * Copy only. The colour swatches, images, and interaction stay code-driven.
   */
  shadeShowcase?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  compare?: {
    enabled?: boolean | null;
    heading?: string | null;
    /**
     * One column per material, in display order.
     */
    columns?:
      | {
          label?: string | null;
          bestFor?: string | null;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          label?: string | null;
          /**
           * Score 1-5, one per column above, same order.
           */
          scores?:
            | {
                score?: number | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Placeholder only. Do not publish attributed customer quotes until they are real and approved.
   */
  testimonials?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          quote?: string | null;
          attribution?: string | null;
          role?: string | null;
          avatar?: (number | null) | Media;
          /**
           * Uncheck only for a real, approved, permissioned testimonial.
           */
          isPlaceholder?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  whyAura?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    items?:
      | {
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  learningHub?: {
    /**
     * Off by default: /guides does not exist yet.
     */
    enabled?: boolean | null;
    heading?: string | null;
    viewAll?: {
      label?: string | null;
      url?: string | null;
    };
    items?:
      | {
          meta?: string | null;
          title?: string | null;
          summary?: string | null;
          url?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Not rendered yet — the current header has no announcement bar.
   */
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandHeading?: string | null;
  brandCopy?: string | null;
  newsletterHeading?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Left empty on purpose. The values currently hardcoded in the footer are unverified placeholders — fill these in with real, confirmed details.
   */
  contact?: {
    companyName?: string | null;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Only add profiles Aura actually owns.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'twitter' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Year is prepended by the frontend.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  paymentSettings?: {
    /**
     * Upload the merchant eSewa QR code image to show at checkout
     */
    esewaQrImage?: (number | null) | Media;
    /**
     * Merchant / Account holder name displayed to customer (e.g. Aura 3D Technologies)
     */
    esewaMerchantName?: string | null;
    /**
     * Optional registered eSewa phone or merchant ID
     */
    esewaId?: string | null;
  };
  /**
   * Temporary development defaults for shipping fees. Update with real business rules before production.
   */
  shippingSettings?: {
    /**
     * Standard flat rate shipping fee in NPR for orders below free shipping threshold (Temporary test default)
     */
    shippingFee?: number | null;
    /**
     * Cart subtotal in NPR required to qualify for free delivery (Temporary test default)
     */
    freeShippingThreshold?: number | null;
    /**
     * Whether qualifying orders receive free delivery (Temporary test default)
     */
    freeShippingEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  categories?:
    | T
    | {
        enabled?: T;
        items?:
          | T
          | {
              title?: T;
              subtitle?: T;
              url?: T;
              image?: T;
              id?: T;
            };
      };
  popular?:
    | T
    | {
        enabled?: T;
        heading?: T;
        products?: T;
      };
  materialsSection?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              material?: T;
              displayName?: T;
              description?: T;
              url?: T;
              id?: T;
            };
      };
  useCases?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              subtitle?: T;
              url?: T;
              image?: T;
              id?: T;
            };
      };
  freshPrints?:
    | T
    | {
        enabled?: T;
        heading?: T;
        viewAll?:
          | T
          | {
              label?: T;
              url?: T;
            };
        products?: T;
      };
  staffPick?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        product?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  shadeShowcase?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  compare?:
    | T
    | {
        enabled?: T;
        heading?: T;
        columns?:
          | T
          | {
              label?: T;
              bestFor?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              label?: T;
              scores?:
                | T
                | {
                    score?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              quote?: T;
              attribution?: T;
              role?: T;
              avatar?: T;
              isPlaceholder?: T;
              id?: T;
            };
      };
  whyAura?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  learningHub?:
    | T
    | {
        enabled?: T;
        heading?: T;
        viewAll?:
          | T
          | {
              label?: T;
              url?: T;
            };
        items?:
          | T
          | {
              meta?: T;
              title?: T;
              summary?: T;
              url?: T;
              image?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandHeading?: T;
  brandCopy?: T;
  newsletterHeading?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        companyName?: T;
        address?: T;
        phone?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  paymentSettings?:
    | T
    | {
        esewaQrImage?: T;
        esewaMerchantName?: T;
        esewaId?: T;
      };
  shippingSettings?:
    | T
    | {
        shippingFee?: T;
        freeShippingThreshold?: T;
        freeShippingEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}